const regions={utc:['UTC','Monde','UTC'],paris:['Paris','France','Europe/Paris'],london:['Londres','Royaume-Uni','Europe/London'],newyork:['New York','États-Unis','America/New_York'],losangeles:['Los Angeles','États-Unis','America/Los_Angeles'],mexico:['Mexico','Mexique','America/Mexico_City'],saopaulo:['São Paulo','Brésil','America/Sao_Paulo'],cairo:['Le Caire','Égypte','Africa/Cairo'],johannesburg:['Johannesburg','Afrique du Sud','Africa/Johannesburg'],dubai:['Dubai','Émirats','Asia/Dubai'],mumbai:['Mumbai','Inde','Asia/Kolkata'],singapore:['Singapore','Singapour','Asia/Singapore'],tokyo:['Tokyo','Japon','Asia/Tokyo'],seoul:['Séoul','Corée du Sud','Asia/Seoul'],shanghai:['Shanghai','Chine','Asia/Shanghai'],sydney:['Sydney','Australie','Australia/Sydney'],auckland:['Auckland','Nouvelle-Zélande','Pacific/Auckland']};
const YEAR_START=1900,YEAR_END=2030;const isMenu=!document.querySelector('#clock');if(isMenu)renderMenu();else startClock();
function renderMenu(){const menu=document.querySelector('#clock-menu');if(!menu)return;menu.innerHTML=Object.entries(regions).map(([key,[name]])=>`<a class="clock-button" href="clock.html?zone=${encodeURIComponent(key)}"><h2>${name}</h2></a>`).join('');}
function parts(date,zone){const v={};new Intl.DateTimeFormat('en-US',{timeZone:zone,hour12:false,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',fractionalSecondDigits:3}).formatToParts(date).forEach(p=>v[p.type]=p.value);return{year:+v.year,month:+v.month,day:+v.day,hour:+v.hour,minute:+v.minute,second:+v.second,ms:+(v.fractionalSecond||0)};}
function days(y,m){return new Date(Date.UTC(y,m,0)).getUTCDate();}
function startClock(){const key=new URLSearchParams(location.search).get('zone')||'utc';const[name,country,zone]=regions[key]||regions.utc;const canvas=document.querySelector('#clock'),ctx=canvas.getContext('2d');let calendar=false;document.querySelector('#name').textContent=name;document.querySelector('#country').textContent=country;document.title=`Clock Expansion — ${name}`;window.addEventListener('clock-mode',e=>{calendar=!!e.detail.calendar;});
function ring(x,y,r,color,w,a=.15){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.strokeStyle=color;ctx.lineWidth=w;ctx.globalAlpha=a;ctx.stroke();ctx.globalAlpha=1;}function text(v,x,y,color,size){ctx.fillStyle=color;ctx.font=`600 ${size}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(v,x,y);}function laser(x,y,r,p,color){const q=Math.max(8,r*Math.min(1,Math.max(.06,p)));ctx.save();ctx.strokeStyle=color;ctx.shadowColor=color;ctx.shadowBlur=16;ctx.lineWidth=Math.max(2,r*.018);ctx.beginPath();ctx.moveTo(x-q,y);ctx.lineTo(x+q,y);ctx.moveTo(x,y-q);ctx.lineTo(x,y+q);ctx.stroke();ctx.restore();}
function labels(x,y,r,count,color,active,size){ring(x,y,r,color,1,.18);for(let n=1;n<=count;n++){const a=-Math.PI/2+n*Math.PI*2/count;if(count>100&&n%100!==0&&n!==active)continue;text(String(n),x+Math.cos(a)*r,y+Math.sin(a)*r,color,n===active?size+2:size);}}
function draw(t){const b=canvas.getBoundingClientRect(),d=devicePixelRatio||1,w=Math.max(1,b.width),h=Math.max(1,b.height),x=w/2,y=h/2,base=Math.max(8,Math.min(w,h)/2-28)/13.6;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const dc=days(t.year,t.month),sec=(t.second+t.ms/1000)/60,min=(t.minute+sec)/60,hr=(t.hour+min)/24,day=(t.day-1+(t.hour+t.minute/60)/24)/dc,mon=(t.month-1+day)/12,yr=(t.year-YEAR_START+mon)/(YEAR_END-YEAR_START+1);const rings=calendar?[[base,base*3,day,'#70baff',3],[base*3,base*6,mon,'#a98cff',3],[base*6,base*13,yr,'#fff',4]]:[[base,base*2.5,t.ms/1000,'#ff79c6',2],[base*2.5,base*5,sec,'#ff5267',2],[base*5,base*7.8,min,'#ffd34e',3],[base*7.8,base*10.8,hr,'#55e7cf',3]];rings.forEach(([i,o,p,c,z])=>{ring(x,y,i,c,z);ring(x,y,o,c,1,.08);ring(x,y,i+(o-i)*Math.max(0,Math.min(1,p)),c,z+2*(1-p),.9*(1-p)+.12);});if(calendar){labels(x,y,base*2.35,dc,'#70baff',t.day,8);labels(x,y,base*5.25,12,'#a98cff',t.month,8);labels(x,y,base*12.3,YEAR_END-YEAR_START+1,'#fff',t.year,5);laser(x,y,base*13,yr,'#fff');}else{labels(x,y,base*2.2,10,'#ff79c6',Math.floor(t.ms/100),7);labels(x,y,base*4.7,60,'#ff5267',t.second,7);labels(x,y,base*7.5,60,'#ffd34e',t.minute,7);labels(x,y,base*10.3,24,'#55e7cf',t.hour,8);laser(x,y,base*10.8,hr,'#55e7cf');}}
function update(){const t=parts(new Date(),zone);document.querySelector('#time').textContent=`${String(t.hour).padStart(2,'0')}:${String(t.minute).padStart(2,'0')}:${String(t.second).padStart(2,'0')}.${String(t.ms).padStart(3,'0')}`;document.querySelector('#date').textContent=new Intl.DateTimeFormat('fr',{timeZone:zone,dateStyle:'full'}).format(new Date());draw(t);}update();setInterval(update,50);addEventListener('resize',update);}
